openapi: 3.0.3
info:
  title: demo API
  description: demom API
  version: 0.0.1
servers:
  - url: http://127.0.0.1:8080/demo
    description: host url
paths:
  /board:
    get:
      summary: 모든 게시물을 가져옴
      description: 모든 게시물을 가져옴
      responses:
        '200':    # status code
          description: 모든 게시물의 리스트
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    content:
                      type: string
                    name:
                      type: string
    post:
      summary: 게시물등록
      description: 게시물등록
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                name:
                  type: string
      responses:
        '200':    # status code
          description: 모든 게시물의 리스트
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    content:
                      type: string
                    name:
                      type: string
  /board/{id}: 
    parameters: 
      - name: id
        in: path
        required: true
        description: 수정할 게시물의 id
        schema:
          type: integer
          format: int64
          minimum: 1
          default: 1
    put:
      summary: 게시물 수정
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                name:
                  type: string
      responses:
        '200':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  content:
                    type: string
                  name:
                    type: string
    delete:
      summary: 게시물 삭제
      responses:
        '200':
          description: created
          content:
            application/json:
              schema:
                type: boolean